# Constants
D_r: 0.067 # rotation diffusion coefficient
D: 0. # translational diffusion coefficient

# Parameters
dim: 3 # dimension of the problem
v0: 10. # ABP speed
w0: 1. # scale of angular velocity
vec_I: [0., 0., -1.] # light direction (unit vector)

# Simulation parameters
dt: 0.1 # time step
Nt: 5 # number of time steps
N: 32000 # number of samples/ABPs

# Saving
save_every: 1

# Beam parameters
magnitude: 1.


