# Constants
D_r: 0.067 # rotation diffusion coefficient
D: 0. # translational diffusion coefficient

# Parameters
dim: 3 # dimension of the problem
v0: 1. # ABP speed
w0: 1. # scale of angular velocity
vec_I: [0., 0., -1.] # light direction (unit vector)

# Simulation parameters
dt: 0.01 # time step
Nt: 10000 # number of time steps
N: 100 # number of samples/ABPs